const express = require('express');
const router = express.Router();
const dbService = require('../services/dbService');
const PDFDocument = require('pdfkit');

const TABLE_NAME = 'reports';

// In-memory file storage for hackathon to avoid complex catalyst file store setup
const fileStorage = new Map();

// Helper to escape CSV fields
const escapeCSV = (field) => {
  if (field === null || field === undefined) return '""';
  const str = String(field);
  if (str.includes(',') || str.includes('\n') || str.includes('"')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return `"${str}"`;
};

// POST generate report
router.post('/generate', async (req, res) => {
  try {
    const { type, format, filters, officer } = req.body;
    
    let firs = await dbService.getAllRows(req, 'firs').catch(() => []);
    const officers = await dbService.getAllRows(req, 'officers').catch(() => []);
    
    // Apply Filters
    if (filters) {
      if (filters.crimeCategory) firs = firs.filter(f => f.crimeCategory === filters.crimeCategory);
      if (filters.district) firs = firs.filter(f => f.district === filters.district);
      if (filters.policeStation) firs = firs.filter(f => f.policeStation && f.policeStation.toLowerCase().includes(filters.policeStation.toLowerCase()));
      if (filters.status) firs = firs.filter(f => f.status === filters.status);
      if (filters.severity) firs = firs.filter(f => f.priorityLevel === filters.severity);
      if (filters.dateStart) {
        const start = new Date(filters.dateStart).getTime();
        firs = firs.filter(f => new Date(f.incidentDate).getTime() >= start);
      }
      if (filters.dateEnd) {
        const end = new Date(filters.dateEnd).getTime();
        firs = firs.filter(f => new Date(f.incidentDate).getTime() <= end);
      }
    }
    
    const fileId = `rep_${Date.now()}_${Math.floor(Math.random() * 1000)}`;
    const fileName = `AI_CIOS_Report_${Date.now()}.${format}`;
    
    let fileBuffer;
    let contentType;
    
    if (format === 'pdf') {
      contentType = 'application/pdf';
      fileBuffer = await new Promise((resolve) => {
        const doc = new PDFDocument({ margin: 50, size: 'A4', layout: 'landscape' });
        let buffers = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        
        // Build PDF Header
        doc.fontSize(24).font('Helvetica-Bold').text('KARNATAKA STATE POLICE', { align: 'center' });
        doc.fontSize(16).font('Helvetica').text('Crime Intelligence Operations System (AI-CIOS)', { align: 'center' });
        doc.moveDown(2);
        
        // Report Metadata
        doc.fontSize(18).font('Helvetica-Bold').text('Official Case Summary Report');
        doc.moveDown();
        doc.fontSize(12).font('Helvetica').text(`Generated By: ${officer || 'Authorized Officer'}`);
        doc.text(`Timestamp: ${new Date().toLocaleString()}`);
        doc.text(`Total Records Analyzed: ${firs.length}`);
        
        // Active Filters
        if (filters && Object.values(filters).some(v => v)) {
          doc.moveDown();
          doc.font('Helvetica-Bold').text('Applied Filters:');
          doc.font('Helvetica');
          Object.entries(filters).forEach(([k, v]) => {
            if (v) doc.text(`- ${k.charAt(0).toUpperCase() + k.slice(1)}: ${v}`);
          });
        }
        
        doc.moveDown(2);
        
        // Build Data Table manually in PDFKit
        doc.font('Helvetica-Bold').fontSize(10);
        const startY = doc.y;
        const columnPositions = {
          col1: 50,  // FIR Number
          col2: 180, // Category
          col3: 320, // District
          col4: 450, // Status
          col5: 560, // Date
          col6: 700  // Priority
        };
        
        // Header row
        doc.text('FIR Number', columnPositions.col1, startY);
        doc.text('Crime Category', columnPositions.col2, startY);
        doc.text('District', columnPositions.col3, startY);
        doc.text('Status', columnPositions.col4, startY);
        doc.text('Incident Date', columnPositions.col5, startY);
        doc.text('Priority', columnPositions.col6, startY);
        
        doc.moveTo(50, startY + 15).lineTo(790, startY + 15).stroke();
        
        let currentY = startY + 25;
        doc.font('Helvetica').fontSize(9);
        
        firs.forEach((f, idx) => {
          if (currentY > 500) {
            doc.addPage({ layout: 'landscape' });
            currentY = 50;
            // Redraw Header
            doc.font('Helvetica-Bold').fontSize(10);
            doc.text('FIR Number', columnPositions.col1, currentY);
            doc.text('Crime Category', columnPositions.col2, currentY);
            doc.text('District', columnPositions.col3, currentY);
            doc.text('Status', columnPositions.col4, currentY);
            doc.text('Incident Date', columnPositions.col5, currentY);
            doc.text('Priority', columnPositions.col6, currentY);
            doc.moveTo(50, currentY + 15).lineTo(790, currentY + 15).stroke();
            currentY += 25;
            doc.font('Helvetica').fontSize(9);
          }
          
          doc.text(f.firNumber || 'N/A', columnPositions.col1, currentY, { width: 120 });
          doc.text(f.crimeCategory || 'N/A', columnPositions.col2, currentY, { width: 130 });
          doc.text(f.district || 'N/A', columnPositions.col3, currentY, { width: 120 });
          doc.text(f.status || 'N/A', columnPositions.col4, currentY, { width: 100 });
          doc.text(f.incidentDate ? new Date(f.incidentDate).toLocaleDateString() : 'N/A', columnPositions.col5, currentY, { width: 130 });
          doc.text(f.priorityLevel || 'N/A', columnPositions.col6, currentY, { width: 80 });
          
          doc.moveTo(50, currentY + 15).lineTo(790, currentY + 15).strokeColor('#E2E8F0').stroke();
          doc.strokeColor('#000000'); // reset
          currentY += 25;
        });
        
        // Footer
        let pages = doc.bufferedPageRange();
        for (let i = 0; i < pages.count; i++) {
          doc.switchToPage(i);
          doc.fontSize(8).text(
            `Page ${i + 1} of ${pages.count} | AI-CIOS Confidential`,
            50,
            doc.page.height - 50,
            { align: 'center' }
          );
        }
        
        doc.end();
      });
      
    } else if (format === 'csv') {
      contentType = 'text/csv';
      
      const headers = [
        'Case Number', 'Crime Type', 'Location', 'District', 'Police Station', 
        'Officer Name', 'Date', 'Status', 'Priority', 'Victim Count', 
        'Suspect Count', 'Latitude', 'Longitude'
      ].map(escapeCSV).join(',');
      
      const rows = firs.map(f => {
        const off = officers.find(o => o.id === f.officerId) || { name: 'Unknown' };
        let victimCount = 0;
        let suspectCount = 0;
        try { victimCount = JSON.parse(f.victims || '[]').length; } catch(e){}
        try { suspectCount = JSON.parse(f.accused || '[]').length; } catch(e){}
        
        return [
          f.firNumber,
          f.crimeCategory,
          f.description,
          f.district,
          f.policeStation,
          off.name,
          f.incidentDate ? new Date(f.incidentDate).toISOString() : 'N/A',
          f.status,
          f.priorityLevel,
          victimCount,
          suspectCount,
          f.latitude,
          f.longitude
        ].map(escapeCSV).join(',');
      });
      
      fileBuffer = Buffer.from('\uFEFF' + headers + '\n' + rows.join('\n'), 'utf-8'); // UTF-8 BOM
    } else {
      return res.status(400).json({ error: 'Unsupported format' });
    }
    
    // Store in memory
    fileStorage.set(fileId, {
      buffer: fileBuffer,
      contentType,
      fileName
    });
    
    // Save metadata
    await dbService.insertRow(req, TABLE_NAME, {
      reportId: fileId,
      reportType: type,
      officer: officer || 'Investigator',
      generatedAt: new Date().toISOString(),
      downloadUrl: `/reports/download/${fileId}`
    }).catch(err => console.error('Failed to save history', err));
    
    res.json({
      success: true,
      downloadUrl: `/reports/download/${fileId}`,
      message: 'Report compiled successfully'
    });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Failed to generate report' });
  }
});

// GET download file
router.get('/download/:id', (req, res) => {
  const fileData = fileStorage.get(req.params.id);
  if (!fileData) {
    return res.status(404).json({ error: 'File not found or expired' });
  }
  
  res.setHeader('Content-Type', fileData.contentType);
  res.setHeader('Content-Disposition', `attachment; filename="${fileData.fileName}"`);
  res.send(fileData.buffer);
});

// GET all reports history
router.get('/', async (req, res) => {
  try {
    const records = await dbService.getAllRows(req, TABLE_NAME).catch(() => []);
    // Sort descending by default
    records.sort((a, b) => new Date(b.generatedAt).getTime() - new Date(a.generatedAt).getTime());
    res.json(records);
  } catch (error) {
    res.status(500).json({ error: 'Failed to fetch reports' });
  }
});

// DELETE a report
router.delete('/:id', async (req, res) => {
  try {
    const record = await dbService.getRow(req, TABLE_NAME, req.params.id);
    if (record && record.reportId) {
      fileStorage.delete(record.reportId);
    }
    await dbService.deleteRow(req, TABLE_NAME, req.params.id);
    res.json({ success: true });
  } catch (error) {
    res.status(500).json({ error: 'Failed to delete report' });
  }
});

module.exports = router;
