const express = require('express');
const router = express.Router();
const dbService = require('../services/dbService');
const PDFDocument = require('pdfkit');

const TABLE_NAME = 'reports';

// In-memory file storage for hackathon to avoid complex catalyst file store setup
const fileStorage = new Map();

// POST generate report
router.post('/generate', async (req, res) => {
  try {
    const { type, format, filters, officer } = req.body;
    
    let firs = await dbService.getAllRows(req, 'firs');
    // simple mock filter
    if (filters && filters.crimeCategory) {
      firs = firs.filter(f => f.crimeCategory === filters.crimeCategory);
    }
    
    const fileId = `rep_${Date.now()}_${Math.floor(Math.random() * 1000)}`;
    const fileName = `AI_CIOS_${type.replace(/\s+/g, '_')}_${Date.now()}.${format}`;
    
    let fileBuffer;
    let contentType;
    
    if (format === 'pdf') {
      contentType = 'application/pdf';
      fileBuffer = await new Promise((resolve) => {
        const doc = new PDFDocument({ margin: 50 });
        let buffers = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        
        // Build PDF
        doc.fontSize(20).text('AI-CIOS Crime Intelligence Report', { align: 'center' });
        doc.moveDown();
        doc.fontSize(14).text(`Report Type: ${type}`);
        doc.fontSize(12).text(`Generated By: ${officer || 'Investigator'}`);
        doc.fontSize(12).text(`Date: ${new Date().toLocaleString()}`);
        doc.moveDown();
        
        doc.fontSize(16).text('Executive Summary');
        doc.fontSize(12).text(`This report contains an analysis based on the current filtering parameters. We have evaluated ${firs.length} related records from the Catalyst Data Store.`);
        doc.moveDown();
        
        doc.fontSize(16).text('Case Statistics');
        firs.slice(0, 5).forEach((f, idx) => {
          doc.fontSize(10).text(`${idx + 1}. FIR Number: ${f.firNumber} | District: ${f.district} | Crime: ${f.crimeCategory} | Status: ${f.status}`);
        });
        
        if (firs.length > 5) {
          doc.moveDown();
          doc.text(`... and ${firs.length - 5} more cases.`);
        }
        
        doc.moveDown();
        doc.fontSize(16).text('AI Insights');
        doc.fontSize(10).text('The automated risk evaluation shows standard patterns consistent with historical records. Targeted monitoring is advised for hotspots.');
        
        // Footer
        doc.fontSize(8).text('Generated securely by Zoho Catalyst - AI-CIOS Backend', 50, 700, { align: 'center' });
        
        doc.end();
      });
    } else if (format === 'csv') {
      contentType = 'text/csv';
      const headers = ['FIR Number', 'District', 'Police Station', 'Crime Category', 'Status', 'Date'].join(',');
      const rows = firs.map(f => `${f.firNumber},${f.district},${f.policeStation},${f.crimeCategory},${f.status},${f.incidentDate}`).join('\n');
      fileBuffer = Buffer.from(headers + '\n' + rows, 'utf-8');
    } else {
      return res.status(400).json({ error: 'Unsupported format' });
    }
    
    // Store in memory mock file store
    fileStorage.set(fileId, {
      buffer: fileBuffer,
      contentType,
      fileName
    });
    
    // Save metadata to Catalyst
    const newRecord = await dbService.insertRow(req, TABLE_NAME, {
      reportId: fileId,
      reportType: type,
      officer: officer || 'Investigator',
      timestamp: new Date().toISOString(),
      downloadUrl: `/api/catalyst/reports/download/${fileId}`
    }).catch(err => console.error('Failed to save history', err));
    
    res.json({
      success: true,
      downloadUrl: `/api/catalyst/reports/download/${fileId}`,
      message: 'Report compiled successfully'
    });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Failed to generate report' });
  }
});

// GET download file
router.get('/download/:id', (req, res) => {
  const fileData = fileStorage.get(req.params.id);
  if (!fileData) {
    return res.status(404).json({ error: 'File not found or expired' });
  }
  
  res.setHeader('Content-Type', fileData.contentType);
  res.setHeader('Content-Disposition', `attachment; filename="${fileData.fileName}"`);
  res.send(fileData.buffer);
});

// GET all reports history
router.get('/', async (req, res) => {
  try {
    const records = await dbService.getAllRows(req, TABLE_NAME);
    res.json(records);
  } catch (error) {
    res.status(500).json({ error: 'Failed to fetch reports' });
  }
});

// DELETE a report
router.delete('/:id', async (req, res) => {
  try {
    const record = await dbService.getRow(req, TABLE_NAME, req.params.id);
    if (record && record.reportId) {
      fileStorage.delete(record.reportId);
    }
    const deletedRecord = await dbService.deleteRow(req, TABLE_NAME, req.params.id);
    res.json({ success: true, deletedRecord });
  } catch (error) {
    res.status(500).json({ error: 'Failed to delete report' });
  }
});

module.exports = router;
