const express = require('express');
const router = express.Router();
const dbService = require('../services/dbService');
const {
  parseJSON,
  detectLanguage,
  classifyIntent,
  extractFiltersAndQuery,
  generateGroundedResponse
} = require('../services/aiIntelligenceEngine');

const HISTORY_TABLE = 'ai_history';
const FIRS_TABLE = 'firs';

// POST chat analysis (Strict Intent-Driven RAG Pipeline)
router.post('/chat', async (req, res) => {
  try {
    const { query = '', messages = [], context = {}, language = 'en' } = req.body;
    const cleanQuery = query ? query.trim() : '';

    // 1. Language & Intent Detection
    const detectedLang = detectLanguage(cleanQuery, language);
    const intent = classifyIntent(cleanQuery, context);

    // 2. ONLY Query Database if the intent actually requires crime/FIR records
    const requiresCrimeData = [
      'crime_search',
      'count',
      'highest_risk',
      'case_details',
      'repeat_offenders',
      'translate'
    ].includes(intent.type);

    let allFirs = [];
    let filteredFirs = [];
    let updatedContext = { ...context };

    if (requiresCrimeData) {
      allFirs = await dbService.getAllRows(req, FIRS_TABLE);
      const extracted = extractFiltersAndQuery(allFirs, cleanQuery, context);
      filteredFirs = extracted.filteredFirs;
      updatedContext = extracted.context;
    }

    // 3. Generate Grounded AI Response
    let groundedResult = generateGroundedResponse(
      intent,
      cleanQuery,
      filteredFirs,
      allFirs,
      detectedLang,
      updatedContext,
      messages
    );

    // 4. If QuickML is configured, enhance ONLY genuine crime investigation searches
    if (requiresCrimeData && intent.type === 'crime_search') {
      try {
        const quickmlService = require('../services/quickmlService');
        const isKn = detectedLang === 'kn' || detectedLang === 'mixed';

        const conversationMemory = messages.slice(-4).map(msg => ({
          role: msg.role === 'assistant' ? 'assistant' : msg.role === 'system' ? 'system' : 'user',
          content: msg.content
        }));

        const systemPrompt = `You are the lead AI Crime Intelligence Assistant for the Karnataka State Police (AI-CIOS).
Analyze the provided live case records, extract evidence, detect suspect connections, and answer the investigator's question.
Cite exact FIR numbers, police stations, and districts from the context. Do not invent fictitious case numbers.
${isKn
  ? 'CRITICAL MANDATORY INSTRUCTION: You MUST generate your entire response in natural, fluent, complete Kannada (ಕನ್ನಡ ಭಾಷೆ). Do not produce mixed English sentences. Every paragraph, explanation, recommendation, and summary MUST be in Kannada. Only unavoidable technical terms (FIR, IP, CCTV, API, SQL) and proper noun identifiers may remain in English.'
  : 'CRITICAL INSTRUCTION: Output MUST be concise, professional, and directly answer the query in English.'}`;

        const userPrompt = `User Query: "${cleanQuery}"
Requested Language: ${isKn ? 'Kannada (ಕನ್ನಡ)' : 'English'}
Intent: ${intent.type}
Retrieved Live Database Cases (${filteredFirs.length} matches):
${JSON.stringify(filteredFirs.slice(0, 4).map(c => ({
  firNumber: c.firNumber,
  crimeCategory: c.crimeCategory,
  description: c.description,
  district: c.district,
  policeStation: c.policeStation,
  incidentDate: c.incidentDate,
  status: c.status,
  priority: c.priorityLevel || c.priority,
  accused: parseJSON(c.accused, []),
  evidence: parseJSON(c.evidence, []),
  applicableActs: parseJSON(c.applicableActs, [])
})), null, 2)}

Provide a complete, comprehensive, and grounded response answering the user query in ${isKn ? '100% fluent Kannada' : 'English'}.`;

        const messagesPayload = [
          { role: 'system', content: systemPrompt },
          ...conversationMemory,
          { role: 'user', content: userPrompt }
        ];

        const aiSummary = await quickmlService.chatWithGLM(req, messagesPayload);
        if (aiSummary && aiSummary.trim()) {
          groundedResult.summary = aiSummary.trim();
        }
      } catch (err) {
        // High quality fallback already generated by generateGroundedResponse
      }
    }

    const responsePayload = {
      ...groundedResult,
      updatedContext
    };

    // Save conversation step to history asynchronously
    dbService.insertRow(req, HISTORY_TABLE, {
      query: cleanQuery,
      response: responsePayload.summary,
      language: detectedLang
    }).catch(err => console.error("History save failed:", err.message));

    res.json(responsePayload);
  } catch (error) {
    console.error('AI Chat Error:', error);
    res.status(500).json({ error: 'Failed to process AI chat query' });
  }
});

// GET all AI history
router.get('/', async (req, res) => {
  try {
    const records = await dbService.getAllRows(req, HISTORY_TABLE);
    res.json(records);
  } catch (error) {
    res.status(500).json({ error: 'Failed to fetch AI history' });
  }
});

// GET an AI history record by id
router.get('/:id', async (req, res) => {
  try {
    const record = await dbService.getRow(req, HISTORY_TABLE, req.params.id);
    if (record) {
      res.json(record);
    } else {
      res.status(404).json({ error: 'AI history record not found' });
    }
  } catch (error) {
    res.status(500).json({ error: 'Failed to fetch AI history record' });
  }
});

// DELETE an AI history record
router.delete('/:id', async (req, res) => {
  try {
    const deletedRecord = await dbService.deleteRow(req, HISTORY_TABLE, req.params.id);
    res.json({ success: true, deletedRecord });
  } catch (error) {
    res.status(500).json({ error: 'Failed to delete AI history record' });
  }
});

module.exports = router;
